// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MemoryStore is an autogenerated mock type for the MemoryStore type
type MemoryStore struct {
	mock.Mock
}

// Begin provides a mock function with given fields:
func (_m *MemoryStore) Begin() {
	_m.Called()
}

// Commit provides a mock function with given fields:
func (_m *MemoryStore) Commit() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Count provides a mock function with given fields: value
func (_m *MemoryStore) Count(value string) {
	_m.Called(value)
}

// Delete provides a mock function with given fields: key
func (_m *MemoryStore) Delete(key string) {
	_m.Called(key)
}

// Get provides a mock function with given fields: key
func (_m *MemoryStore) Get(key string) error {
	ret := _m.Called(key)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RollBack provides a mock function with given fields:
func (_m *MemoryStore) RollBack() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Set provides a mock function with given fields: key, value
func (_m *MemoryStore) Set(key string, value string) {
	_m.Called(key, value)
}
